### ISSUE TITLE
bug: Not a single page/component, module based, has been migrated to their standalone equivalent.

### ISSUE THREAD

**Issue by JulienLecoq** [ionic-team/ionic-angular-standalone-codemods#36]
### Prerequisites

- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-angular-standalone-codemods) that already report this problem, without success.

### Codemod version

0.0.7

### Current Behavior

It does not appears that a single file has been migrated correctly.

No modules are removed. 
standalone: true is not added
IonicModule is correctly replaced by IonToolbar, IonHeader, IonContent etc

I get warnings about the fact that dynamic ion-icon names couldn't be migrated.

The terminal logs that the project migration is successful whereas it's not.

### Expected Behavior

Modules should be removed, standalone: true should be added to components, there should be no error about dynamic ion-icon names and the tool should not says that the migration is successful if it's not.

### Steps to Reproduce

I just used the command: ``npx @ionic/angular-standalone-codemods`` at the root of my Ionic project.

I can't share it since it's a private project.

**Comment by rdlabo** [comment]
@JulienLecoq To use this library, Angular product must first be configured as Standalone.

Please run `ng generate @angular/core:standalone` first.

**Comment by sean-perkins** [comment]
Closing this issue due to a lack of response. 

This project helps with migrating an existing Ionic application using `IonicModule` to using Ionic's standalone components, it does not migrate your Angular project to use standalone components for your own components. It looks like there is an Angular provided schematic to help with that migration.

Please open a new issue if I misunderstood your question with additional context/reproduction of your problem. Thanks!
